//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTcms.EFAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_users
    {
        public int id { get; set; }
        public Nullable<int> site_id { get; set; }
        public Nullable<int> group_id { get; set; }
        public string user_name { get; set; }
        public string salt { get; set; }
        public string password { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string avatar { get; set; }
        public string nick_name { get; set; }
        public string sex { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string telphone { get; set; }
        public string area { get; set; }
        public string address { get; set; }
        public string qq { get; set; }
        public string msn { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> point { get; set; }
        public Nullable<int> exp { get; set; }
        public Nullable<byte> status { get; set; }
        public Nullable<System.DateTime> reg_time { get; set; }
        public string reg_ip { get; set; }
        public Nullable<int> age { get; set; }
        public string openid { get; set; }
        public string interest { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public Nullable<double> accuracy { get; set; }
        public string address_component { get; set; }
        public string unionid { get; set; }
    }
}
