//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTcms.EFAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TouristDBEntities : DbContext
    {
        public TouristDBEntities()
            : base("name=TouristDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dt_channel_article_news> dt_channel_article_news { get; set; }
        public virtual DbSet<dt_channel_article_food> dt_channel_article_food { get; set; }
        public virtual DbSet<dt_channel_article_guidance> dt_channel_article_guidance { get; set; }
    }
}
