//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTcms.School
{
    using System;
    using System.Collections.Generic;
    
    public partial class University_Enroll_Status
    {
        public string University_ID { get; set; }
        public string 院校简介 { get; set; }
        public string 公立_私立 { get; set; }
        public string 校园位置 { get; set; }
        public string 犯罪率_犯罪数量_学生数量_ { get; set; }
        public string 地理位置 { get; set; }
        public string 校园 { get; set; }
        public string 宿舍 { get; set; }
        public Nullable<int> US_NEWS_排名 { get; set; }
        public Nullable<int> TIMES_排名 { get; set; }
        public Nullable<int> QS_排名 { get; set; }
        public Nullable<int> ARWU_排名 { get; set; }
        public Nullable<int> 录取难度 { get; set; }
        public Nullable<double> 录取率 { get; set; }
        public Nullable<int> 录取数量 { get; set; }
        public Nullable<double> 录取后入学比例 { get; set; }
        public Nullable<double> 申请者高中成绩前50_比例 { get; set; }
        public Nullable<double> 申请者高中成绩前10_比例 { get; set; }
        public Nullable<double> SAT语言_GAO { get; set; }
        public Nullable<double> SAT语言_DI { get; set; }
        public Nullable<double> SAT数学_GAO { get; set; }
        public Nullable<double> SAT数学_DI { get; set; }
        public Nullable<double> SAT写作_GAO { get; set; }
        public Nullable<double> SAT写作_DI { get; set; }
        public Nullable<double> ACT综合_GAO { get; set; }
        public Nullable<double> ACT综合_DI { get; set; }
        public Nullable<double> 州外学生比例 { get; set; }
        public Nullable<int> 本科生数量 { get; set; }
        public Nullable<int> 研究生数量 { get; set; }
        public Nullable<int> 学生组织数量 { get; set; }
        public Nullable<int> 兄弟会数量 { get; set; }
        public Nullable<int> 姐妹会数量 { get; set; }
        public Nullable<double> 学术族裔分布_白 { get; set; }
        public Nullable<double> 学术族裔分布_亚洲 { get; set; }
        public Nullable<double> 学术族裔分布_黑 { get; set; }
        public Nullable<double> 学杂费_州内_ { get; set; }
        public Nullable<double> 总体花费_州内_ { get; set; }
        public Nullable<double> 学杂费_州外_ { get; set; }
        public Nullable<double> 总体花费_州外 { get; set; }
        public string 事实 { get; set; }
        public string 知名校友 { get; set; }
        public string 体育 { get; set; }
        public string 图片 { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    }
}
