//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTcms.School
{
    using System;
    using System.Collections.Generic;
    
    public partial class University_Master_CN
    {
        public int University_ID { get; set; }
        public string University_Code { get; set; }
        public string UniversityName_CN { get; set; }
        public string UniversityName_EN { get; set; }
        public string Country { get; set; }
        public string CityName { get; set; }
        public string Picture { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    }
}
