//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTcms.School
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Bachelor_Log
    {
        public string ID { get; set; }
        public string User_ID { get; set; }
        public string Target_Country { get; set; }
        public Nullable<double> GPA_Four { get; set; }
        public Nullable<double> GPA_Hundred { get; set; }
        public Nullable<double> TOEFL { get; set; }
        public Nullable<double> IELTS { get; set; }
        public Nullable<double> SAT { get; set; }
        public Nullable<double> ACT { get; set; }
        public string Target_JoinTime { get; set; }
        public string Prefed_SchoolType { get; set; }
        public string MiddleSchool_Type { get; set; }
        public string MiddleSchool_GradeLevel { get; set; }
        public string Recommendation { get; set; }
        public string Award { get; set; }
        public string Summer_Program { get; set; }
        public string Volunteer_Experience { get; set; }
        public Nullable<System.DateTime> Insert_Date { get; set; }
    }
}
