//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTcms.EFAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_course_status
    {
        public int course_status_id { get; set; }
        public string course_status_en { get; set; }
        public string course_status_ch { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    }
}
