//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTcms.EFAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_teacher_master
    {
        public int teacher_id { get; set; }
        public string teacher_name_en { get; set; }
        public string teacher_name_ch { get; set; }
        public string teacher_country { get; set; }
        public string teacher_pic { get; set; }
        public string teacher_desc { get; set; }
        public Nullable<System.DateTime> teacher_join_date { get; set; }
        public Nullable<int> teacher_status { get; set; }
    }
}
