//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTcms.EFAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Sex { get; set; }
        public string Age { get; set; }
        public string OpenID { get; set; }
        public string WechatID { get; set; }
        public string WechatName { get; set; }
        public string Zuoyouming { get; set; }
        public string Picture { get; set; }
        public string Region { get; set; }
        public string Address { get; set; }
        public string MiddleSchool { get; set; }
        public string University_Bechelar { get; set; }
        public string University_Master { get; set; }
        public string University_Doctor { get; set; }
        public string Majoy_Bechelar { get; set; }
        public string Major_Master { get; set; }
        public string GPA { get; set; }
        public string GRE { get; set; }
        public string GMAT { get; set; }
        public string TOFEL { get; set; }
        public string SAT1 { get; set; }
        public string IELTS { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Xueli { get; set; }
        public string Zhuanye { get; set; }
    }
}
